// Code generated by MockGen. DO NOT EDIT.
// Source: limiter.go

// Package mock_limiter is a generated GoMock package.
package mock_limiter

import (
	limiter "github.com/amobe/d-back/pkg/limiter"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockLimiter is a mock of Limiter interface
type MockLimiter struct {
	ctrl     *gomock.Controller
	recorder *MockLimiterMockRecorder
}

// MockLimiterMockRecorder is the mock recorder for MockLimiter
type MockLimiterMockRecorder struct {
	mock *MockLimiter
}

// NewMockLimiter creates a new mock instance
func NewMockLimiter(ctrl *gomock.Controller) *MockLimiter {
	mock := &MockLimiter{ctrl: ctrl}
	mock.recorder = &MockLimiterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockLimiter) EXPECT() *MockLimiterMockRecorder {
	return m.recorder
}

// RequestToken mocks base method
func (m *MockLimiter) RequestToken() (limiter.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestToken")
	ret0, _ := ret[0].(limiter.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RequestToken indicates an expected call of RequestToken
func (mr *MockLimiterMockRecorder) RequestToken() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestToken", reflect.TypeOf((*MockLimiter)(nil).RequestToken))
}

// Cancel mocks base method
func (m *MockLimiter) Cancel() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cancel")
}

// Cancel indicates an expected call of Cancel
func (mr *MockLimiterMockRecorder) Cancel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockLimiter)(nil).Cancel))
}
