// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_iplimiter is a generated GoMock package.
package mock_iplimiter

import (
	entity "github.com/amobe/d-back/pkg/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// AcceptRequest mocks base method
func (m *MockService) AcceptRequest(ipAddress entity.IPAddress) (entity.RequestToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptRequest", ipAddress)
	ret0, _ := ret[0].(entity.RequestToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptRequest indicates an expected call of AcceptRequest
func (mr *MockServiceMockRecorder) AcceptRequest(ipAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptRequest", reflect.TypeOf((*MockService)(nil).AcceptRequest), ipAddress)
}
